// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcy17iM9MjY63UTjH-GUvV5Zb3vMN4sr8',
    appId: '1:838834807225:web:1b343468bdb7774d0a5668',
    messagingSenderId: '838834807225',
    projectId: 'chat-13f26',
    authDomain: 'chat-13f26.firebaseapp.com',
    storageBucket: 'chat-13f26.appspot.com',
    measurementId: 'G-0HZ2CS26WH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi4KW2pzKwCmj1FcjCVy9ssjNJa5SA0w0',
    appId: '1:838834807225:android:c4f2bfcbddd147820a5668',
    messagingSenderId: '838834807225',
    projectId: 'chat-13f26',
    storageBucket: 'chat-13f26.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj1SEe0kTXkfJI7I4O2fTAUS8jUQDDM4s',
    appId: '1:838834807225:ios:6fefdb3e689be0270a5668',
    messagingSenderId: '838834807225',
    projectId: 'chat-13f26',
    storageBucket: 'chat-13f26.appspot.com',
    iosClientId: '838834807225-d2rcoee64hul2j5kicf35pth9dno29vr.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatWithFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBj1SEe0kTXkfJI7I4O2fTAUS8jUQDDM4s',
    appId: '1:838834807225:ios:9f81c0dd202229600a5668',
    messagingSenderId: '838834807225',
    projectId: 'chat-13f26',
    storageBucket: 'chat-13f26.appspot.com',
    iosClientId: '838834807225-i9pvr4jp7vrnufveo7qc7ff0t7gnvo5p.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatWithFlutter.RunnerTests',
  );
}
